# Generated by Django 2.1.1 on 2019-04-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='age',
            field=models.IntegerField(default='0', max_length=140),
        ),
    ]
