# Generated by Django 2.1.1 on 2019-04-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0003_auto_20190403_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='gender',
            field=models.BooleanField(choices=[(True, 'Male'), (False, 'Female')], default=True),
        ),
    ]
