# Generated by Django 2.1.1 on 2019-04-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0004_hotel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='gender',
            field=models.BooleanField(choices=[(True, 'Male'), (False, 'Female')], default=''),
        ),
    ]
